# Generated by Django 5.1.6 on 2025-03-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_specialofferimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellerimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='feautureproductimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='recentproductimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
