# Generated by Django 5.1.6 on 2025-03-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_product_bestsellerimage_best_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='feautureproduct',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='recentproduct',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='specialoffer',
            name='discount_price',
        ),
    ]
